=== jonesthesoftware/LaunchBoxLauncher/xsd/LauncherEmulator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="DefaultEnum" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="autoboot" />
            <xs:enumeration value="rompath" />
            <xs:enumeration value="program" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ParameterType">
        <xs:sequence>
            <xs:choice>
                <xs:element name="Constant" type="xs:string" minOccurs="0"/>
                <xs:element name="Default" type="DefaultEnum" minOccurs="0"/>
                <xs:element name="Variable" type="xs:string" minOccurs="0"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="Switch" type="xs:string"/>
        <xs:attribute name="MameAutoboot" type="xs:boolean" default="false"/>
        <!-- I did consider placing the switch separator at the higher level, but some emulators seem to use different separators for different options -->
        <xs:attribute name="SwitchSeparator" type="xs:string" default=" "/>
    </xs:complexType>

    <xs:complexType name="ParameterListType">
        <xs:sequence>
            <xs:element name="Parameter" type="ParameterType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CommandLineType">
        <xs:sequence>
            <xs:element name="ParameterList" type="ParameterListType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LaunchboxEmulatorType">
        <xs:sequence>
            <xs:choice>
                <xs:element name="ID"/>
                <xs:element name="Title"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="BespokeEmulatorType">
        <xs:sequence>
            <xs:element name="EmulatorPath" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EmulatorDefinitionType">
        <xs:sequence>
            <xs:choice>
                <xs:element name="LaunchboxEmulator" type="LaunchboxEmulatorType" minOccurs="0"/>
                <xs:element name="BespokeEmulator" type="BespokeEmulatorType" minOccurs="0"/>
            </xs:choice>
            <xs:element name="CommandLine" type="CommandLineType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="PrototypeType">
        <xs:sequence>
            <xs:element name="EmulatorDefinition" type="EmulatorDefinitionType"/>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="PrototypeReferenceType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="ref" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="EmulatorType">
        <xs:sequence>
            <xs:element name="Prototype" type="PrototypeReferenceType" minOccurs="0"/>
            <xs:element name="EmulatorDefinition" type="EmulatorDefinitionType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string"/>
        <xs:attribute name="prototype" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="LauncherEmulatorType">
        <xs:sequence>
            <xs:element name="Prototype" type="PrototypeType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Emulator" type="EmulatorType" minOccurs="0" maxOccurs="unbounded">
                <xs:keyref name="EmulatorPrototype" refer="PrototypeKey">
                    <xs:selector xpath="Emulator"/>
                    <xs:field xpath="@prototype"/>
                </xs:keyref>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="LauncherEmulator" type="LauncherEmulatorType">
        <xs:key name="PrototypeKey">
            <xs:selector xpath="Prototype"/>
            <xs:field xpath="@key"/>
        </xs:key>
        <xs:key name="EmulatorKey">
            <xs:selector xpath="Emulator"/>
            <xs:field xpath="@key"/>
        </xs:key>
    </xs:element>

</xs:schema>

=== jonesthesoftware/LaunchBoxLauncher/xml/examples/AlternativeSetup/LauncherEmulator.xml
<?xml version="1.0" encoding="UTF-8"?>
<LauncherEmulator
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../xsd/LauncherEmulator.xsd">

<!-- 
    Note that in these examples the prototypes both contain a rompath switch
    I personally store the bios for each machine / machine grouping in its own folder
    In the configuration I then defined the rompath for each machine
 -->

<!-- 
    Instead of looking up the executable path from Launchbox you can define where the executable is directly
    You'll need to change the path to wherever you want to launch the emulator from
-->
    <Prototype key="BespokeMame">
        <EmulatorDefinition>
            <BespokeEmulator>
                <EmulatorPath>V:\Emulators\Arcade\mame0235b\mame.exe</EmulatorPath>
            </BespokeEmulator>
            <CommandLine>
                <ParameterList>
                    <Parameter>
                        <Variable>system</Variable>
                    </Parameter>
                    <Parameter Switch="-keyboardprovider">
                        <Constant>dinput</Constant>
                    </Parameter>
                    <Parameter Switch="-skip_gameinfo"/>
                    <Parameter Switch="-nowindow"/>
                    <Parameter Switch="-rompath">
                        <Variable>biospath</Variable>
                    </Parameter>
                </ParameterList>
            </CommandLine>
        </EmulatorDefinition>
    </Prototype>

<!-- 
    The executable will be looked up in the Launchbox XML files, so if you change the directory for MAME there then the directory mame runs from
    here will change, both methods have their own benefits.
-->
    <Prototype key="Mame">
        <EmulatorDefinition>
            <LaunchboxEmulator>
                <Title>MAME</Title>
            </LaunchboxEmulator>
            <CommandLine>
                <ParameterList>
                    <Parameter>
                        <Variable>system</Variable>
                    </Parameter>
                    <Parameter Switch="-keyboardprovider">
                        <Constant>dinput</Constant>
                    </Parameter>
                    <Parameter Switch="-skip_gameinfo"/>
                    <Parameter Switch="-nowindow"/>
                    <Parameter Switch="-video">
                        <Constant>bgfx</Constant>
                    </Parameter>
                    <Parameter Switch="-bgfx_screen_chains">
                        <Constant>crt-geom</Constant>
                    </Parameter>
                    <Parameter Switch="-rompath">
                        <Variable>biospath</Variable>
                    </Parameter>
                </ParameterList>
            </CommandLine>
        </EmulatorDefinition>
    </Prototype>

    <Emulator key="MameFloppyAutoboot" prototype="Mame">
        <EmulatorDefinition>
            <CommandLine>
                <ParameterList>
                    <Parameter Switch="-flop1">
                        <Default>rompath</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_command">
                        <Default>autoboot</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_delay">
                        <Constant>2</Constant>
                    </Parameter>
                </ParameterList>
            </CommandLine>
        </EmulatorDefinition>
    </Emulator>

    <Emulator key="MameAcornDFSAutoboot" prototype="BespokeMame">
        <EmulatorDefinition>
            <CommandLine>
                <ParameterList>
                    <Parameter Switch="-exp">
                        <Variable>exp1</Variable>
                    </Parameter>
                    <Parameter Switch="-cart1">
                        <Variable>cart1</Variable>
                    </Parameter>
                    <Parameter Switch="-flop">
                        <Default>rompath</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_command">
                        <Default>autoboot</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_delay">
                        <Constant>2</Constant>
                    </Parameter>
                </ParameterList>
            </CommandLine>
        </EmulatorDefinition>
    </Emulator>

    <Emulator key="MameAcornTapeAutoboot" prototype="BespokeMame">
        <EmulatorDefinition>
            <CommandLine>
                <ParameterList>
                    <Parameter Switch="-cass">
                        <Default>rompath</Default>
                    </Parameter>
                    <Parameter Switch="-exp">
                        <Variable>exp1</Variable>
                    </Parameter>
                    <Parameter Switch="-autoboot_command">
                        <Default>autoboot</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_delay">
                        <Constant>2</Constant>
                    </Parameter>
                </ParameterList>
            </CommandLine>
        </EmulatorDefinition>
    </Emulator>

    <Emulator key="MameTapeAutoboot" prototype="Mame">
        <EmulatorDefinition>
            <CommandLine>
                <ParameterList>
                    <Parameter Switch="-cass">
                        <Default>rompath</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_command">
                        <Default>autoboot</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_delay">
                        <Variable>autobootDelay</Variable>
                    </Parameter>
                </ParameterList>
            </CommandLine>
        </EmulatorDefinition>
    </Emulator>

    <Emulator key="MameLuaDiskAutoboot" prototype="Mame">
        <EmulatorDefinition>
            <CommandLine>
                <ParameterList>
                    <Parameter Switch="-flop1">
                        <Default>rompath</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_script">
                        <Variable>luaScriptPath</Variable>
                    </Parameter>
                    <Parameter Switch="-autoboot_delay">
                        <Variable>autobootDelay</Variable>
                    </Parameter>
                </ParameterList>
            </CommandLine>
        </EmulatorDefinition>
    </Emulator>

</LauncherEmulator>

=== jonesthesoftware/LaunchBoxLauncher/xml/LauncherEmulator.xml
<?xml version="1.0" encoding="UTF-8"?>
<LauncherEmulator
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/LauncherEmulator.xsd">

    <Prototype key="Mame">
        <EmulatorDefinition>
            <LaunchboxEmulator>
                <Title>MAME 0261</Title>
            </LaunchboxEmulator>
            <CommandLine>
                <ParameterList>
                    <Parameter>
                        <Variable>system</Variable>
                    </Parameter>
                    <Parameter Switch="-keyboardprovider">
                        <Constant>dinput</Constant>
                    </Parameter>
                    <Parameter Switch="-skip_gameinfo"/>
                    <Parameter Switch="-nowindow"/>
                    <Parameter Switch="-video">
                        <Constant>bgfx</Constant>
                    </Parameter>
                    <Parameter Switch="-bgfx_screen_chains">
                        <Constant>crt-geom</Constant>
                    </Parameter>
                </ParameterList>
            </CommandLine>
        </EmulatorDefinition>
    </Prototype>

    <Emulator key="MameFloppyAutoboot" prototype="Mame">
        <EmulatorDefinition>
            <CommandLine>
                <ParameterList>
                    <Parameter Switch="-flop1">
                        <Default>rompath</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_command">
                        <Default>autoboot</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_delay">
                        <Constant>2</Constant>
                    </Parameter>
                </ParameterList>
            </CommandLine>
        </EmulatorDefinition>
    </Emulator>

    <Emulator key="MameAcornDFSAutoboot" prototype="Mame">
        <EmulatorDefinition>
            <CommandLine>
                <ParameterList>
                    <Parameter Switch="-exp">
                        <Variable>exp1</Variable>
                    </Parameter>
                    <Parameter Switch="-cart1">
                        <Variable>cart1</Variable>
                    </Parameter>
                    <Parameter Switch="-flop">
                        <Default>rompath</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_command">
                        <Default>autoboot</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_delay">
                        <Constant>2</Constant>
                    </Parameter>
                </ParameterList>
            </CommandLine>
        </EmulatorDefinition>
    </Emulator>

    <Emulator key="MameAcornTapeAutoboot" prototype="Mame">
        <EmulatorDefinition>
            <CommandLine>
                <ParameterList>
                    <Parameter Switch="-cass">
                        <Default>rompath</Default>
                    </Parameter>
                    <Parameter Switch="-exp">
                        <Variable>exp1</Variable>
                    </Parameter>
                    <Parameter Switch="-autoboot_command">
                        <Default>autoboot</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_delay">
                        <Constant>2</Constant>
                    </Parameter>
                </ParameterList>
            </CommandLine>
        </EmulatorDefinition>
    </Emulator>

    <Emulator key="MameTapeAutoboot" prototype="Mame">
        <EmulatorDefinition>
            <CommandLine>
                <ParameterList>
                    <Parameter Switch="-cass">
                        <Default>rompath</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_command">
                        <Default>autoboot</Default>
                    </Parameter>
                    <Parameter Switch="-autoboot_delay">
                        <Variable>autobootDelay</Variable>
                    </Parameter>
                </ParameterList>
            </CommandLine>
        </EmulatorDefinition>
    </Emulator>

</LauncherEmulator>
