=== jonesthesoftware/LaunchBoxLauncher/xsd/LauncherAutoboot.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    
    <xs:complexType name="CommandSequenceType">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="Command" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="KnownBootSequenceType">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="Command" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="AutobootType">
        <xs:sequence>
            <xs:element name="NamedProgramBootSequence" type="CommandSequenceType" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="DefaultLuaScriptPath" type="xs:string"/>
                <xs:element name="DefaultBootSequence" type="CommandSequenceType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="LauncherAutobootType">
        <xs:sequence>
            <xs:element name="Autoboot" type="AutobootType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="LauncherAutoboot" type="LauncherAutobootType">
        <xs:key name="AutobootKey">
            <xs:selector xpath="Autoboot"/>
            <xs:field xpath="@key"/>
        </xs:key>
    </xs:element>

</xs:schema>

=== jonesthesoftware/LaunchBoxLauncher/xml/examples/AlternativeSetup/LauncherAutoboot.xml
<?xml version="1.0" encoding="UTF-8"?>
<LauncherAutoboot
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../xsd/LauncherAutoboot.xsd">
    
    <Autoboot key="AtomDisk">
        <NamedProgramBootSequence>
            <Command><![CDATA[*DOS]]></Command>
            <Command><![CDATA[*RUN """%program%"""]]></Command>
            <Command/>
        </NamedProgramBootSequence>
        <DefaultBootSequence>
            <Command><![CDATA[*DOS]]></Command>
            <Command><![CDATA[*CAT]]></Command>
            <Command/>
            <Command/>
            <Command><![CDATA[*RUN "]]></Command>
        </DefaultBootSequence>
    </Autoboot>

    <Autoboot key="BBCDisk">
        <DefaultBootSequence>
            <Command><![CDATA[*EXEC !BOOT]]></Command>
            <Command/>
        </DefaultBootSequence>
    </Autoboot>

    <Autoboot key="AcornElectronTape">
        <DefaultBootSequence>
            <Command><![CDATA[*TAPE]]></Command>
            <Command><![CDATA[CHAIN """"""]]></Command>
            <Command/>
        </DefaultBootSequence>
    </Autoboot>

    <Autoboot key="DragonTape">
        <DefaultBootSequence>
            <Command><![CDATA[CLOADM:EXEC]]></Command>
            <Command/>
        </DefaultBootSequence>
    </Autoboot>

</LauncherAutoboot>
